#!/bin/bash -e
wget -O"${DEBIRF_ROOT}/tmp/hwraid.key" http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key
debirf_exec apt-key add /tmp/hwraid.key

debirf_exec apt-get update
debirf_exec apt-get --assume-yes install megacli

# dwipe fork https://github.com/martijnvanbrummelen/nwipe
debirf_exec apt-get --assume-yes install nwipe
