#!/bin/bash -e
wget -O"${DEBIRF_ROOT}/tmp/wmf-apt.key" http://apt.wikimedia.org/autoinstall/keyring/wikimedia-archive-keyring.gpg
debirf_exec apt-key add /tmp/wmf-apt.key

debirf_exec apt-get -q update
debirf_exec apt-get --assume-yes install megacli hpssacli

# dwipe fork https://github.com/martijnvanbrummelen/nwipe
debirf_exec apt-get --assume-yes install nwipe
